// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!! This file is auto-generated by Reflang. !!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#include <algorithm>
#include <cassert>
#include <stdexcept>
#include <string>
#include <type_traits>

#include "lib/reflang.hpp"

namespace reflang
{

/*
Class 'Test::ComplexType'.
Methods:
Members:
*/


/*
Class 'MyClass'.
Methods:
Members:
> int member
> const int const_member
> int * pointer_member
> const int * const_pointer_member
> const int *const const_pointer_const_member
> int & ref_member
> const int & const_ref_member
> ComplexType complex
> const ComplexType const_complex
> ComplexType * pointer_complex
> const ComplexType * const_pointer_complex
> const ComplexType *const const_pointer_const_complex
> ComplexType & ref_complex
> const ComplexType & const_ref_complex
*/


}  // namespace reflang
