// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!! This file is auto-generated by Reflang. !!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#ifndef REFLANG_METADATA_SUBCLASS_GEN_HPP
#define REFLANG_METADATA_SUBCLASS_GEN_HPP

#include <string>

#include "lib/reflang.hpp"
#include "subclass.src.hpp"

namespace reflang
{


template <>
class Class<MyClass::Subclass> : public IClass
{
public:
	static const constexpr int FieldCount = 1;
	static const constexpr int StaticFieldCount = 1;
	static const constexpr int MethodCount = 1;
	static const constexpr int StaticMethodCount = 1;

	int GetFieldCount() const override;
	Reference GetField(
			const Reference& o, const std::string& name) const override;

	int GetStaticFieldCount() const override;
	Reference GetStaticField(const std::string& name) const override;

	int GetMethodCount() const override;
	std::vector<std::unique_ptr<IMethod>> GetMethod(
			const std::string& name) const override;

	int GetStaticMethodCount() const override;
	std::vector<std::unique_ptr<IFunction>> GetStaticMethod(
			const std::string& name) const override;

	const std::string& GetName() const override;

	// Calls T::operator() on each field of 'MyClass::Subclass'.
	// Works well with C++14 generic lambdas.
	template <typename T>
	static void IterateFields(const MyClass::Subclass& c, T t);

	template <typename T>
	static void IterateFields(MyClass::Subclass& c, T t);

	template <typename T>
	static void IterateStaticFields(T t);
};

template <typename T>
void Class<MyClass::Subclass>::IterateFields(const MyClass::Subclass& c, T t)
{
	t(c.field);
}

template <typename T>
void Class<MyClass::Subclass>::IterateFields(MyClass::Subclass& c, T t)
{
	t(c.field);
}

template <typename T>
void Class<MyClass::Subclass>::IterateStaticFields(T t)
{
	t(MyClass::Subclass::static_field);
}

// MyClass::Subclass methods metadata.
template <>
class Method<decltype(&MyClass::Subclass::method), &MyClass::Subclass::method> : public IMethod
{
public:
	const std::string& GetName() const override;
	int GetParameterCount() const override;
	Object Invoke(const Reference& o, const std::vector<Object>& args) override;
};

// End of MyClass::Subclass methods metadata.
// MyClass::Subclass static methods metadata.

template <>
class Function<void(*)(), MyClass::Subclass::static_method> : public IFunction
{
	int GetParameterCount() const override;

	const std::string& GetName() const override;

	Object Invoke(const std::vector<Object>& args) override;
};
// End of MyClass::Subclass static methods metadata.



}  // namespace reflang

#endif //REFLANG_METADATA_SUBCLASS_GEN_HPP
