// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!! This file is auto-generated by Reflang. !!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#include <algorithm>
#include <cassert>
#include <stdexcept>
#include <string>
#include <type_traits>

#include "lib/reflang.hpp"

namespace reflang
{

template <>
class Function<decltype(Func), Func> : public IFunction
{
	int GetParameterCount() const override
	{
		return 1;
	}

	const std::string& GetName() const override
	{
		static const std::string name = "Func";
		return name;
	}

	Object Invoke(const std::vector<Object>& args) override
	{
		if (args.size() != 1)
		{
			throw std::invalid_argument("count");
		}
		if (!args[0].IsT<std::decay_t<int>>())
		{
			throw std::invalid_argument("a");
		}

		Func(args[0].GetT<std::decay_t<int>>());
		return Object();
	}
};

namespace
{
	// Object to auto-register Func.
	struct Func_registrar
	{
		Func_registrar()
		{
			::reflang::registry::internal::Register(
				std::make_unique<
					Function<
						decltype(Func),
						Func>>());
		}
	} Func_instance;
}


template <>
class Function<decltype(Func2), Func2> : public IFunction
{
	int GetParameterCount() const override
	{
		return 2;
	}

	const std::string& GetName() const override
	{
		static const std::string name = "Func2";
		return name;
	}

	Object Invoke(const std::vector<Object>& args) override
	{
		if (args.size() != 2)
		{
			throw std::invalid_argument("count");
		}
		if (!args[0].IsT<std::decay_t<int>>())
		{
			throw std::invalid_argument("a");
		}
		if (!args[1].IsT<std::decay_t<float>>())
		{
			throw std::invalid_argument("b");
		}

		return Object(Func2(args[0].GetT<std::decay_t<int>>(), args[1].GetT<std::decay_t<float>>()));
	}
};

namespace
{
	// Object to auto-register Func2.
	struct Func2_registrar
	{
		Func2_registrar()
		{
			::reflang::registry::internal::Register(
				std::make_unique<
					Function<
						decltype(Func2),
						Func2>>());
		}
	} Func2_instance;
}


template <>
class Function<decltype(Func3), Func3> : public IFunction
{
	int GetParameterCount() const override
	{
		return 1;
	}

	const std::string& GetName() const override
	{
		static const std::string name = "Func3";
		return name;
	}

	Object Invoke(const std::vector<Object>& args) override
	{
		if (args.size() != 1)
		{
			throw std::invalid_argument("count");
		}
		if (!args[0].IsT<std::decay_t<const int &>>())
		{
			throw std::invalid_argument("a");
		}

		return Object(Func3(args[0].GetT<std::decay_t<const int &>>()));
	}
};

namespace
{
	// Object to auto-register Func3.
	struct Func3_registrar
	{
		Func3_registrar()
		{
			::reflang::registry::internal::Register(
				std::make_unique<
					Function<
						decltype(Func3),
						Func3>>());
		}
	} Func3_instance;
}


}  // namespace reflang
