// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!! This file is auto-generated by Reflang. !!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#ifndef REFLANG_METADATA_OVERLOAD_GEN_HPP
#define REFLANG_METADATA_OVERLOAD_GEN_HPP

#include <string>

#include "lib/reflang.hpp"
#include "overload.src.hpp"

namespace reflang
{


template <>
class Function<void(*)(), Func> : public IFunction
{
	int GetParameterCount() const override;
	Parameter GetReturnType() const override;
	Parameter GetParameter(int i) const override;

	const std::string& GetName() const override;

	Object Invoke(const std::vector<Object>& args) override;
};



template <>
class Function<void(*)(int), Func> : public IFunction
{
	int GetParameterCount() const override;
	Parameter GetReturnType() const override;
	Parameter GetParameter(int i) const override;

	const std::string& GetName() const override;

	Object Invoke(const std::vector<Object>& args) override;
};



template <>
class Function<void(*)(float), Func> : public IFunction
{
	int GetParameterCount() const override;
	Parameter GetReturnType() const override;
	Parameter GetParameter(int i) const override;

	const std::string& GetName() const override;

	Object Invoke(const std::vector<Object>& args) override;
};



template <>
class Function<bool(*)(const char &), Func> : public IFunction
{
	int GetParameterCount() const override;
	Parameter GetReturnType() const override;
	Parameter GetParameter(int i) const override;

	const std::string& GetName() const override;

	Object Invoke(const std::vector<Object>& args) override;
};


}  // namespace reflang

#endif //REFLANG_METADATA_OVERLOAD_GEN_HPP
