// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!! This file is auto-generated by Reflang. !!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#include "overload.gen.hpp"

#include <algorithm>
#include <cassert>
#include <stdexcept>
#include <type_traits>

namespace reflang
{


int Function<void(), Func>::GetParameterCount() const
{
	return 0;
}

static const std::string Func_name = "Func";

const std::string& Function<void(), Func>::GetName() const
{
	return Func_name;
}

Object Function<void(), Func>::Invoke(const std::vector<Object>& args)
{
	if (args.size() != 0)
	{
		throw std::invalid_argument("count");
	}

	Func();
	return Object();
}

namespace
{
	// Object to auto-register Func.
	struct Func_registrar
	{
		Func_registrar()
		{
			::reflang::registry::internal::Register(
					std::make_unique<Function<void(), Func>>());
		}
	} Func_instance;
}



int Function<void(int), Func>::GetParameterCount() const
{
	return 1;
}

static const std::string Func_1_name = "Func";

const std::string& Function<void(int), Func>::GetName() const
{
	return Func_1_name;
}

Object Function<void(int), Func>::Invoke(const std::vector<Object>& args)
{
	if (args.size() != 1)
	{
		throw std::invalid_argument("count");
	}
	if (!args[0].IsT<std::decay_t<int>>())
	{
		throw std::invalid_argument("i");
	}

	Func(args[0].GetT<std::decay_t<int>>());
	return Object();
}

namespace
{
	// Object to auto-register Func.
	struct Func_1_registrar
	{
		Func_1_registrar()
		{
			::reflang::registry::internal::Register(
					std::make_unique<Function<void(int), Func>>());
		}
	} Func_1_instance;
}



int Function<void(float), Func>::GetParameterCount() const
{
	return 1;
}

static const std::string Func_2_name = "Func";

const std::string& Function<void(float), Func>::GetName() const
{
	return Func_2_name;
}

Object Function<void(float), Func>::Invoke(const std::vector<Object>& args)
{
	if (args.size() != 1)
	{
		throw std::invalid_argument("count");
	}
	if (!args[0].IsT<std::decay_t<float>>())
	{
		throw std::invalid_argument("f");
	}

	Func(args[0].GetT<std::decay_t<float>>());
	return Object();
}

namespace
{
	// Object to auto-register Func.
	struct Func_2_registrar
	{
		Func_2_registrar()
		{
			::reflang::registry::internal::Register(
					std::make_unique<Function<void(float), Func>>());
		}
	} Func_2_instance;
}



int Function<bool(const char &), Func>::GetParameterCount() const
{
	return 1;
}

static const std::string Func_3_name = "Func";

const std::string& Function<bool(const char &), Func>::GetName() const
{
	return Func_3_name;
}

Object Function<bool(const char &), Func>::Invoke(const std::vector<Object>& args)
{
	if (args.size() != 1)
	{
		throw std::invalid_argument("count");
	}
	if (!args[0].IsT<std::decay_t<const char &>>())
	{
		throw std::invalid_argument("c");
	}

	return Object(Func(args[0].GetT<std::decay_t<const char &>>()));
}

namespace
{
	// Object to auto-register Func.
	struct Func_3_registrar
	{
		Func_3_registrar()
		{
			::reflang::registry::internal::Register(
					std::make_unique<Function<bool(const char &), Func>>());
		}
	} Func_3_instance;
}


}  // namespace reflang
