// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!! This file is auto-generated by Reflang. !!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#include <cassert>
#include <string>

#include "lib/reflang.hpp"

namespace reflang
{

/*
Function 'ns::NamespacedFunction()':
> void NamespacedFunction();
*/
/*
Function 'GlobalFunction()':
> void GlobalFunction();
*/
}  // namespace reflang
