// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!! This file is auto-generated by Reflang. !!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#include "void-noargs.gen.hpp"

#include <algorithm>
#include <cassert>
#include <stdexcept>
#include <type_traits>

namespace reflang
{


int Function<decltype(ns::NamespacedFunction), ns::NamespacedFunction>::GetParameterCount() const
{
	return 0;
}

static const std::string ns__NamespacedFunction_name = "ns::NamespacedFunction";

const std::string& Function<decltype(ns::NamespacedFunction), ns::NamespacedFunction>::GetName() const
{
	return ns__NamespacedFunction_name;
}

Object Function<decltype(ns::NamespacedFunction), ns::NamespacedFunction>::Invoke(const std::vector<Object>& args)
{
	if (args.size() != 0)
	{
		throw std::invalid_argument("count");
	}

	ns::NamespacedFunction();
	return Object();
}

namespace
{
	// Object to auto-register ns::NamespacedFunction.
	struct ns__NamespacedFunction_registrar
	{
		ns__NamespacedFunction_registrar()
		{
			::reflang::registry::internal::Register(
				std::make_unique<
					Function<
						decltype(ns::NamespacedFunction),
						ns::NamespacedFunction>>());
		}
	} ns__NamespacedFunction_instance;
}



int Function<decltype(GlobalFunction), GlobalFunction>::GetParameterCount() const
{
	return 0;
}

static const std::string GlobalFunction_name = "GlobalFunction";

const std::string& Function<decltype(GlobalFunction), GlobalFunction>::GetName() const
{
	return GlobalFunction_name;
}

Object Function<decltype(GlobalFunction), GlobalFunction>::Invoke(const std::vector<Object>& args)
{
	if (args.size() != 0)
	{
		throw std::invalid_argument("count");
	}

	GlobalFunction();
	return Object();
}

namespace
{
	// Object to auto-register GlobalFunction.
	struct GlobalFunction_registrar
	{
		GlobalFunction_registrar()
		{
			::reflang::registry::internal::Register(
				std::make_unique<
					Function<
						decltype(GlobalFunction),
						GlobalFunction>>());
		}
	} GlobalFunction_instance;
}


}  // namespace reflang
